### ISSUE TITLE
The Tensorflow version used in the code is outdated

### ISSUE THREAD

**Issue by loongx2** [PacktPublishing/Hands-On-Natural-Language-Processing-with-Python#8]
The Tensorflow version used in the codes are outdated and will soon be deprecated. There are errors prompting all over

**Comment by sonam-packt** [comment]
Hello @loongx2,

Yes, you're right. This book was published in 2018 and we used the TensorFlow version available at the time. We are currently working on a book that uses the latest TensorFlow version, which will come out next year.

In the meanwhile, if you're looking for a book on NLP, we have published a few this year that might interest you.
